spring:
  application:
    name: consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/metrics
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true